name: Build and Publish JAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3. Make gradlew executable
      - name: Grant execute permission
        run: chmod +x gradlew

      # 4. Build the project
      - name: Clean & build with Gradle
        run: ./gradlew clean build --no-daemon

      # 5. Upload the .jar(s) as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-jar
          path: build/libs/*.jar
